#include "socket/tcp_client.h"
#include "win_sock.h"
#include <winsock2.h>
#include <ws2tcpip.h>
namespace {constexpr Socket invalidSocket=static_cast<Socket>(INVALID_SOCKET);SOCKET native(Socket s){return static_cast<SOCKET>(s);}uint32_t readSocket(Socket s,char* o,uint32_t z,uint32_t t){uint32_t nread=0;while(nread<z){if(t){fd_set f;FD_ZERO(&f);FD_SET(native(s),&f);timeval v{static_cast<long>(t/1000000),static_cast<long>(t%1000000)};if(select(0,&f,nullptr,nullptr,&v)<=0)break;}int n=recv(native(s),o+nread,z-nread,0);if(n<=0)break;nread+=static_cast<uint32_t>(n);}return nread;}uint32_t writeSocket(Socket s,const char* d,uint32_t z){uint32_t nwrite=0;while(nwrite<z){int n=send(native(s),d+nwrite,z-nwrite,0);if(n<=0)break;nwrite+=static_cast<uint32_t>(n);}return nwrite;}}
TcpClient::TcpClient():socket_{invalidSocket}{WinSockManager::getInstance();}TcpClient::TcpClient(Endpoint e):socket_{invalidSocket},endpoint_{e}{WinSockManager::getInstance();}TcpClient::~TcpClient(){if(isOpen())close();}
void TcpClient::open(){if(isOpen())throw TcpInterface::Exception::Close("Socket is already opened");socket_=static_cast<Socket>(socket(AF_INET,SOCK_STREAM,IPPROTO_TCP));if(socket_==invalidSocket)throw TcpInterface::Exception::Open("Create socket failed");}
void TcpClient::connect(Endpoint e){if(!isOpen())throw TcpInterface::Exception::Open("Not opened");if(!e.port)throw TcpInterface::Exception::Port("Invalid port");endpoint_=e;sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(e.port);if(inet_pton(AF_INET,e.ip.c_str(),&a.sin_addr)!=1||::connect(native(socket_),reinterpret_cast<sockaddr*>(&a),sizeof(a))==SOCKET_ERROR)throw TcpInterface::Exception::Connect("Connect failed");}
void TcpClient::close(){if(!isOpen())throw TcpInterface::Exception::Close("Socket is not opened");closesocket(native(socket_));socket_=invalidSocket;}bool TcpClient::isOpen()const{return socket_!=invalidSocket;}uint32_t TcpClient::read(char* const o,uint32_t z,uint32_t t)const{if(!isOpen())throw TcpInterface::Exception::Io("Socket is not opened");return readSocket(socket_,o,z,t);}uint32_t TcpClient::write(const char* const d,uint32_t z)const{if(!isOpen())throw TcpInterface::Exception::Io("Socket is not opened");return writeSocket(socket_,d,z);}uint32_t TcpClient::read(Data& d,uint32_t t)const{return read(d.data(),static_cast<uint32_t>(d.size()),t);}uint32_t TcpClient::write(const Data& d)const{return write(d.data(),static_cast<uint32_t>(d.size()));}
